pokemontcg/pokedex/urls.py
from django.urls import path

from . import views

app_name = "pokedex"

urlpatterns = [
    path("searchInput", views.searchInputView, name="searchInput"),
    path("pokemon_list", views.PokemonListView.as_view(), name="pokemon_list"),
    path("trainer_list", views.TrainerListView.as_view(), name="trainer_list"),
    path("energy_list", views.EnergyListView.as_view(), name="energy_list"),
    path("test", views.testView, name="test"),
    path("loadInitialData", views.loadInitialData, name="loadInitialData"),
    path("create/<str:card_id>", views.createPokemonCard, name="create"),
    path("search/<str:card_name>", views.searchView, name="search"),
    path("", views.homeView, name='home'),
    path("bis/<int:pk>", views.PokemonDetailbisView.as_view(), name="pokemon_detail_bis",),
    path( "js/<int:pk>", views.PokemonDetailJsView.as_view(), name="pokemon_detail_js", ),
    path("bisT/<int:pk>", views.TrainerDetailbisView.as_view(), name="trainer_detail_bisT",),
    path( "js/<int:pk>", views.TrainerDetailJsView.as_view(), name="trainer_detail_js", ),
    path("bisE/<int:pk>", views.EnergyDetailbisView.as_view(), name="energy_detail_bisE",),
    path( "js/<int:pk>", views.EnergyDetailJsView.as_view(), name="energy_detail_js", ),
    path("delete/<int:pk>", views.PokemonDeleteView.as_view(),
         name="pokemon_delete"),
    path("energy_delete/<int:pk>", views.EnergyDeleteView.as_view(),
         name="energy_delete"),
    path("trainer_delete/<int:pk>", views.TrainerDeleteView.as_view(),
         name="trainer_delete"),
]

pokemontcg/pokemontcg/urls.py
from django.contrib import admin
from django.urls import path, include

import core.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pokedex/', include('pokedex.urls', namespace='pokedex')),
    path('cardData/', include('cardData.urls', namespace='cardData')),
    path("accounts/", include("django.contrib.auth.urls")),
]

pokemontcg/home/models.py
from django.db import models

# Create your models here.

pokemontcg/pokedex/models.py
from django.db import models

# Create your models here.
class Type(models.Model):
    name = models.CharField()

class Pokemon(models.Model):
    card_id = models.CharField()
    name = models.CharField()
    types = models.ManyToManyField(Type)
    rarity = models.CharField()
    image = models.CharField()
    prices = models.JSONField(default=list)
    highest_market_price = models.FloatField()

    class Meta:
        ordering = ['name']
        
    def __str__(self):
    		return self.name

class Trainer(models.Model):
    card_id = models.CharField(default=None)
    name = models.CharField()
    rarity = models.CharField()
    image = models.CharField()
    prices = models.JSONField(default=list)
    highest_market_price = models.FloatField()
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
    		return self.name

class Energy(models.Model):
    card_id = models.CharField(default=None)
    name = models.CharField()
    image = models.CharField()
    prices = models.JSONField(default=list)
    highest_market_price = models.FloatField()
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
    		return self.name

class PokemonNames(models.Model):
    name = models.CharField(max_length=100)
    
class TrainerNames(models.Model):
    name = models.CharField(max_length=100)

class EnergyNames(models.Model):
    name = models.CharField(max_length=100)

pokemontcg/home/views.py
from django.shortcuts import render

# Create your views here.

pokemontcg/pokedex/views.py
from django.shortcuts import render, redirect

import json
import http.client
import requests
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404

from .models import Pokemon, Type, Trainer, Energy, PokemonNames, TrainerNames,EnergyNames
from django.views.generic import ListView
from django.forms.models import model_to_dict
from django.views.generic import TemplateView
from django.http import JsonResponse
from django.views import View
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import DeleteView



# Create your views here.

class PokemonListView(LoginRequiredMixin, ListView):
    model = Pokemon

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pokemon_names'] = PokemonNames.objects.all()
        return context
    
class PokemonDeleteView(DeleteView):
    model = Pokemon
    success_url = reverse_lazy("pokedex:pokemon_list")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Pokemon card "{pokemon_name}" has been deleted'.format(
                pokemon_name=self.object.name.capitalize()))
        return response
    
class TrainerListView(LoginRequiredMixin, ListView):
    model = Trainer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trainer_names'] = TrainerNames.objects.all()
        return context
    
class TrainerDeleteView(DeleteView):
    model = Trainer
    success_url = reverse_lazy("pokedex:trainer_list")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Trainer card "{trainer_name}" has been deleted'.format(
                trainer_name=self.object.name.capitalize()))
        return response
    
class EnergyListView(LoginRequiredMixin, ListView):
    model = Energy

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['energy_names'] = EnergyNames.objects.all()
        return context
    
class EnergyDeleteView(DeleteView):
    model = Energy
    success_url = reverse_lazy("pokedex:energy_list")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Energy card "{energy_name}" has been deleted'.format(
                energy_name=self.object.name.capitalize()))
        return response

def loadInitialData(request):
    if Type.objects.count() > 0:

        # Add code for message about initial data already loaded
        messages.add_message(
            request, messages.SUCCESS,
            'Types already loaded.'
        )

        print("Type data already loaded")
        return redirect('pokedex:home')
    else:
        api_url = 'https://api.pokemontcg.io/v2/types'
        response = requests.get(api_url)
        types = response.json()
        # print(types['data'])
        for type_name in types['data']:
            print(type_name)
            current_type = Type(
                name = type_name
            )
            current_type.save()

        # Add some cards into the database
        insertInitialCards()
        
        # Add code for message about initial data successfully loading
        messages.add_message(
            request, messages.SUCCESS,
            'Successfully loaded all Types.'
        )

        # print("Type data successfully loaded")
        return redirect('pokedex:home')
    
def insertInitialCards():
    api_url = 'https://api.pokemontcg.io/v2/cards?q=set.id:base1'
    response = requests.get(api_url)
    set_data = response.json()['data']
    for card_data in set_data:
        try:
            if card_data['supertype'] == 'Pokémon':
                conditions = card_data['tcgplayer']['prices']
                highest_market = 0
                for condition in conditions:
                    current_market = card_data['tcgplayer']['prices'][condition]['market']
                    if current_market > highest_market:
                        highest_market = current_market

                current_pokemon = Pokemon(
                    card_id = card_data['id'],
                    name = card_data['name'],
                    rarity = card_data['rarity'],
                    image = card_data['images']['large'],
                    prices = card_data['tcgplayer'],
                    highest_market_price = highest_market,
                )
                current_pokemon.save()

                for type in card_data['types']:
                    current_type = Type.objects.get(name=type)
                    current_pokemon.types.add(current_type)
                current_pokemon.save()

            # Add trainer card data
            elif card_data['supertype'] == 'Trainer':
                conditions = card_data['tcgplayer']['prices']
                highest_market = 0
                for condition in conditions:
                    current_market = card_data['tcgplayer']['prices'][condition]['market']
                    if current_market > highest_market:
                        highest_market = current_market

                current_trainer = Trainer(
                    card_id = card_data['id'],
                    name = card_data['name'],
                    rarity = card_data['rarity'],
                    image = card_data['images']['large'],
                    prices = card_data['tcgplayer'],
                    highest_market_price = highest_market,
                )
                current_trainer.save()
            
            # Add energy card data
            elif card_data['supertype'] == 'Energy':      
                conditions = card_data['tcgplayer']['prices']
                highest_market = 0
                for condition in conditions:
                    current_market = card_data['tcgplayer']['prices'][condition]['market']
                    if current_market > highest_market:
                        highest_market = current_market

                current_energy = Energy(
                    card_id = card_data['id'],
                    name = card_data['name'],
                    image = card_data['images']['large'],
                    prices = card_data['tcgplayer'],
                    highest_market_price = highest_market,
                )
                current_energy.save()
        except KeyError:
            # Add message about missing key from API (NOT MY FAULT BRO)
            print("This card is missing data from API")

def createPokemonCard(request, card_id):
    if Type.objects.count() == 0:
        # Add code for error message about needing to load initial data first
        print("Please load initial data")
        return redirect('pokedex:pokemon_list')

    api_url = 'https://api.pokemontcg.io/v2/cards/{f_cardID}'.format(f_cardID = card_id)
    response = requests.get(api_url)

    if response.status_code == 200:
        card_data = response.json()['data']
        try:
            # Add pokemon type card
            if card_data['supertype'] == 'Pokémon':
                if Pokemon.objects.filter(card_id=card_data['id']).exists():
                    # Add code for error message about card already existing
                    print("Pokemon card already exists")
                    messages.add_message(
                        request, messages.ERROR,
                        'Card "' + card_data['name'] + '" already exists.'
                    )
                    return redirect('pokedex:pokemon_list')
                
                conditions = card_data['tcgplayer']['prices']
                highest_market = 0
                for condition in conditions:
                    current_market = card_data['tcgplayer']['prices'][condition]['market']
                    if current_market == None:
                        continue
                    elif current_market > highest_market:
                        highest_market = current_market

                current_pokemon = Pokemon(
                    card_id = card_data['id'],
                    name = card_data['name'],
                    rarity = card_data['rarity'],
                    image = card_data['images']['large'],
                    prices = card_data['tcgplayer'],
                    highest_market_price = highest_market,
                )
                current_pokemon.save()

                for type in card_data['types']:
                    current_type = Type.objects.get(name=type)
                    current_pokemon.types.add(current_type)
                current_pokemon.save()

            # Add trainer card data
            elif card_data['supertype'] == 'Trainer':
                if Trainer.objects.filter(card_id=card_data['id']).exists():
                    # Add code for error message about card already existing
                    print("Pokemon card already exists")
                    messages.add_message(
                        request, messages.ERROR,
                        'Card "' + card_data['name'] + '" already exists.'
                    )
                    return redirect('pokedex:trainer_list')
                
                conditions = card_data['tcgplayer']['prices']
                highest_market = 0
                for condition in conditions:
                    current_market = card_data['tcgplayer']['prices'][condition]['market']
                    if current_market == None:
                        continue
                    elif current_market > highest_market:
                        highest_market = current_market

                current_trainer = Trainer(

pokemontcg/pokedex/templates/pokedex/energy_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<title>Confirm Delete</title>
<form method="post">{% csrf_token %}
    <br><br>
    <h5 class="display-6"><strong>Are you sure you want to delete the Energy "{{ object.name|title }}"?</strong></h5>
    {{ form.as_p }}
    <input type="submit" value="Confirm" class="btn btn-primary">
    <a href="{% url 'pokedex:energy_detail_bisE' object.id %}" class="btn btn-danger">Go back</a><br/>
</form>
</div>
{% endblock content %}

pokemontcg/pokedex/templates/pokedex/energy_detailbisE.html
{% extends "base.html" %} {% load django_vite %} {% block content %}
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

 	<!-- jQuery library -->
 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
 
 	<!-- Latest compiled JavaScript -->
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 
</head>
<div id="app">
	<app></app>
</div>
{% endblock content %} {% block js %} {{ block.super }}
<script>
	var ext_id = {{ energy_id | safe }};
    var ext_energy_dico = {{ energy_list | safe }};
	var ext_energy_detail_js_url = '{% url 'pokedex:energy_detail_js' energy_id %}';
	var ext_energy_list_url = '{% url 'pokedex:energy_list' %}';
	var ext_energy_delete_url = '{% url 'pokedex:energy_delete' energy_id %}';

</script>
{% vite_hmr_client %} {% vite_asset 'src/apps/energy_detail/energy_detail.js' %} {% endblock js %}

pokemontcg/pokedex/templates/pokedex/energy_list.html
{% extends "base.html" %}


{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Energy List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        .energy {
            display: flex;
            flex-wrap: wrap;
        }
        .energy-card {
            width: calc(20% - 20px); 
            margin-bottom: 20px;
            margin-right: 20px; 
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .energy-img {
            width: 100%;
            height: auto;
            border-bottom: 1px solid #ddd;
        }
        .energy-name {
            padding: 10px;
            background-color: #f5f5f5;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Energy List</h1>
        <div class="energy">
            {% for energy in object_list %}
            <div class="energy-card">
                <a href="{% url 'pokedex:energy_detail_bisE' pk=energy.id %}"> <img class="energy-img" src="{{ energy.image }}" alt="{{ energy.name }}"> </a>
                <div class="energy-name" >{{ energy.name }}</div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

{% endblock content %}

pokemontcg/pokedex/templates/pokedex/home.html
{% extends "base.html" %}

{%block content%}
<title>Home</title>
<h1>
    Welcome to The Pokeymen TCG site
</h1>

<div class="explainer container bg-light rounded border" style="opacity: 0.9">
    <h3>Home</h3>
    <p>
       The landing page for our website. Contains links to other
       apps and a brief overview of them. Please use the load initial data button on the nav bar before using the rest of the site.
    </p>
 </div><br>
 <div class="explainer container bg-light rounded border" style="opacity: 0.9"> 
    <h3>Pokemon, Trainer, Energy List</h3>
    <p>
       Displays a list of all cards in the database. Click on each card in the list to get more
       details about it. You can also delete cards after getting details about it.
    </p>
 </div><br>
 <div class="border explainer container bg-light rounded" style="opacity: 0.9"> 
    <h3>Search for cards</h3>
    <p>
       Displays a page where you can type a pokemon name/card name into a field, and search for pokemon card results based on your text. 
       You can filter the results by rarity, and you can click on a card to add it to your database.
    </p>
 </div>
 <div class="border explainer container bg-light rounded" style="opacity: 0.9"> 
    <h3>Card data</h3>
    <p>
       Displays a page with generated charts giving you general information about your database.
    </p>
 </div>



{% endblock content %}

pokemontcg/pokedex/templates/pokedex/pokedex_search.html
{% extends "base.html" %} 
{% load django_vite %} {% block content %}
<head>
	<title>Search results</title>
	<style>
		body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        .pokemon {
            display: flex;
            flex-wrap: wrap;
        }
        .pokemon-card {
            width: calc(20% - 20px); 
            margin-bottom: 20px;
            margin-right: 20px; 
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
			cursor: pointer;
        }
        .pokemon-img {
            width: 100%;
            height: auto;
            border-bottom: 1px solid #ddd;
        }
        .pokemon-name {
            padding: 10px;
            background-color: #f5f5f5;
            text-align: center;
        }
		.pokemon-rarity {
			padding: 10px;
            background-color: #f5f5f5;
            text-align: center;
		}
        select {
            width: 200px;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            background-color: #f9f9f9;
            color: #333;
            outline: none;
        }
        select option {
            padding: 10px;
        }
        select:focus {
            background-color: #e6f7ff;
            border-color: #66afe9;
        }
	</style>
</head>
<body>
<div id="app">
	<app></app>
</div>
</body>
{% endblock content %} 
{% block js %} {{ block.super }}
<script>
	var ext_search_data = {{ search_data | safe }};
	var ext_card_name = '{{ card_name }}';
	var ext_rarities = {{ rarities | safe }};
	var ext_create_url = '{% url 'pokedex:create' 1 %}'
</script>
{% vite_hmr_client %} {% vite_asset 'src/apps/pokedex_search/pokedex_search.js' %} 
{% endblock js %}

pokemontcg/pokedex/templates/pokedex/pokemon_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<title>Confirm Delete</title>
<form method="post">{% csrf_token %}
    <br><br>
    <h5 class="display-6"><strong>Are you sure you want to delete the Pokemon "{{ object.name|title }}"?</strong></h5>
    {{ form.as_p }}
    <input type="submit" value="Confirm" class="btn btn-primary">
    <a href="{% url 'pokedex:pokemon_detail_bis' object.id %}" class="btn btn-danger">Go back</a><br/>
</form>
</div>
{% endblock content %}

pokemontcg/pokedex/templates/pokedex/pokemon_detailbis.html
{% extends "base.html" %} {% load django_vite %} {% block content %}
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

 	<!-- jQuery library -->
 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
 
 	<!-- Latest compiled JavaScript -->
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 
</head>
<div id="app">
	<app></app>
</div>
{% endblock content %} {% block js %} {{ block.super }}
<script>
	var ext_id = {{ pokemon_id | safe }};
    var ext_pokemon_dico = {{ pokemon_list | safe }};
	var ext_pokemon_detail_js_url = '{% url 'pokedex:pokemon_detail_js' pokemon_id %}';
	var ext_pokemon_list_url = '{% url 'pokedex:pokemon_list' %}';
	var ext_pokemon_delete_url = '{% url 'pokedex:pokemon_delete' pokemon_id %}';
</script>
{% vite_hmr_client %} {% vite_asset 'src/apps/pokemon_detail/pokemon_detail.js' %} {% endblock js %}

pokemontcg/pokedex/templates/pokedex/pokemon_list.html
{% extends "base.html" %}


{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pokedex List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        .pokemon {
            display: flex;
            flex-wrap: wrap;
        }
        .pokemon-card {
            width: calc(20% - 20px); 
            margin-bottom: 20px;
            margin-right: 20px; 
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .pokemon-img {
            width: 100%;
            height: auto;
            border-bottom: 1px solid #ddd;
        }
        .pokemon-name {
            padding: 10px;
            background-color: #f5f5f5;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Pokédex List</h1>
        <div class="pokemon">
            {% for pokemon in object_list %}
            <div class="pokemon-card">
                <a href="{% url 'pokedex:pokemon_detail_bis' pk=pokemon.id %}"> <img class="pokemon-img" src="{{ pokemon.image }}" alt="{{ pokemon.name }}"> </a>
                <div class="pokemon-name" >{{ pokemon.name }}</div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

{% endblock content %}

pokemontcg/pokedex/templates/pokedex/search.html
{% extends "base.html" %}


{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search for Cards</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            text-align: center;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        input[type="text"] {
            width: 250px;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            background-color: #f9f9f9;
            color: #333;
            outline: none;
            transition: border-color 0.3s, box-shadow 0.3s;
        }
        input[type="text"]:focus {
            border-color: #66afe9;
            box-shadow: 0 0 8px rgba(102, 175, 233, 0.6);
        }
        input[type="button"] {
            padding: 10px 20px;
            font-size: 16px;
            border: none;
            border-radius: 4px;
            background-color: #4CAF50;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        input[type="button"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Search for cards</h1>
        <div>
        <input type='text' id='userInput' placeholder='Type card/pokemon name here'>
        <br> <br>
        <input type='button' onclick='loadUrl()' value='Search' />
        </div>
    </div>
</body>
</html>

<script>
    function loadUrl() {
        var userInput = document.getElementById('userInput').value;
        console.log(userInput)
        var baseUrl = '{% url 'pokedex:search' 1 %}'
        baseUrl = baseUrl.slice(0, -1)
        console.log(baseUrl)
        var searchUrl = baseUrl + userInput
        window.location.href = searchUrl
    }
</script>  

{% endblock content %}

pokemontcg/pokedex/templates/pokedex/test.html
{% extends "base.html" %}

{%block content%}
<h1>
    Hello. This is a test.
</h1>
<a href='http://127.0.0.1:8000/pokedex/create'>create</a>
{% endblock content %}

pokemontcg/pokedex/templates/pokedex/trainer_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<title>Confirm Delete</title>
<form method="post">{% csrf_token %}
    <br><br>
    <h5 class="display-6"><strong>Are you sure you want to delete the Trainer "{{ object.name|title }}"?</strong></h5>
    {{ form.as_p }}
    <input type="submit" value="Confirm" class="btn btn-primary">
    <a href="{% url 'pokedex:trainer_detail_bisT' object.id %}" class="btn btn-danger">Go back</a><br/>
</form>
</div>
{% endblock content %}

pokemontcg/pokedex/templates/pokedex/trainer_detailbis.html
{% extends "base.html" %} {% load django_vite %} {% block content %}
<div id="app">
	<app></app>
</div>
{% endblock content %} {% block js %} {{ block.super }}
<script>
	var ext_id = {{ trainer_id | safe }};
    var ext_trainer_dico = {{ trainer_list | safe }};
	var ext_trainer_detail_js_url = '{% url 'pokedex:trainer_detail_js' trainer_id %}';
	var ext_trainer_list_url = '{% url 'pokedex:trainer_list' %}';
</script>
{% vite_hmr_client %} {% vite_asset 'src/apps/trainer_detail/trainer_detail.js' %} {% endblock js %}

pokemontcg/pokedex/templates/pokedex/trainer_detailbisT.html
{% extends "base.html" %} {% load django_vite %} {% block content %}
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

 	<!-- jQuery library -->
 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
 
 	<!-- Latest compiled JavaScript -->
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 
</head>
<div id="app">
	<app></app>
</div>
{% endblock content %} {% block js %} {{ block.super }}
<script>
	var ext_id = {{ trainer_id | safe }};
    var ext_trainer_dico = {{ trainer_list | safe }};
	var ext_trainer_detail_js_url = '{% url 'pokedex:trainer_detail_js' trainer_id %}';
	var ext_trainer_list_url = '{% url 'pokedex:trainer_list' %}';
	var ext_trainer_delete_url = '{% url 'pokedex:trainer_delete' trainer_id %}';

</script>
{% vite_hmr_client %} {% vite_asset 'src/apps/trainer_detail/trainer_detail.js' %} {% endblock js %}

pokemontcg/pokedex/templates/pokedex/trainer_list.html
{% extends "base.html" %}


{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trainer List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        .trainer {
            display: flex;
            flex-wrap: wrap;
        }
        .trainer-card {
            width: calc(20% - 20px); 
            margin-bottom: 20px;
            margin-right: 20px; 
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .trainer-img {
            width: 100%;
            height: auto;
            border-bottom: 1px solid #ddd;
        }
        .trainer-name {
            padding: 10px;
            background-color: #f5f5f5;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Trainer List</h1>
        <div class="trainer">
            {% for trainer in object_list %}
            <div class="trainer-card">
                <a href="{% url 'pokedex:trainer_detail_bisT' pk=trainer.id %}"> <img class="trainer-img" src="{{ trainer.image }}" alt="{{ trainer.name }}"> </a>
                <div class="trainer-name" >{{ trainer.name }}</div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

{% endblock content %}