pokemontcg/cardData/urls.py
from django.urls import path

from . import views

app_name = "cardData"

urlpatterns = [
    path("showData", views.showData, name="showData"),

]

pokemontcg/pokedex/urls.py
from django.urls import path

from . import views

app_name = "pokedex"

urlpatterns = [
    path("searchInput", views.searchInputView, name="searchInput"),
    path("pokemon_list", views.PokemonListView.as_view(), name="pokemon_list"),
    path("trainer_list", views.TrainerListView.as_view(), name="trainer_list"),
    path("energy_list", views.EnergyListView.as_view(), name="energy_list"),
    path("test", views.testView, name="test"),
    path("loadInitialData", views.loadInitialData, name="loadInitialData"),
    path("create/<str:card_id>", views.createPokemonCard, name="create"),
    path("search/<str:card_name>", views.searchView, name="search"),
    path("", views.homeView, name='home'),
    path("bis/<int:pk>", views.PokemonDetailbisView.as_view(), name="pokemon_detail_bis",),
    path( "js/<int:pk>", views.PokemonDetailJsView.as_view(), name="pokemon_detail_js", ),
    path("bisT/<int:pk>", views.TrainerDetailbisView.as_view(), name="trainer_detail_bisT",),
    path( "js/<int:pk>", views.TrainerDetailJsView.as_view(), name="trainer_detail_js", ),
    path("bisE/<int:pk>", views.EnergyDetailbisView.as_view(), name="energy_detail_bisE",),
    path( "js/<int:pk>", views.EnergyDetailJsView.as_view(), name="energy_detail_js", ),
    path("delete/<int:pk>", views.PokemonDeleteView.as_view(),
         name="pokemon_delete"),
    path("energy_delete/<int:pk>", views.EnergyDeleteView.as_view(),
         name="energy_delete"),
    path("trainer_delete/<int:pk>", views.TrainerDeleteView.as_view(),
         name="trainer_delete"),
]

pokemontcg/pokemontcg/urls.py
from django.contrib import admin
from django.urls import path, include

import core.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pokedex/', include('pokedex.urls', namespace='pokedex')),
    path('cardData/', include('cardData.urls', namespace='cardData')),
    path("accounts/", include("django.contrib.auth.urls")),
]

pokemontcg/core/models.py
from django.db import models

# Create your models here.

pokemontcg/core/views.py
from django.shortcuts import render

# Create your views here.

from django.contrib.auth.views import LoginView
from django.contrib.auth import login as auth_login

class CoreLoginView(LoginView):
    template_name = "core/login.html"
    def form_valid(self, form):
        """Security check complete. Log the user in."""
        user = form.get_user()
        auth_login(self.request, user)
        if user_need_to_go_to_otp:
            return redirect('otp_url')
        else:
            return else_where

pokemontcg/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    {% block head %}
    {% endblock head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
         <!-- Latest compiled and minified CSS -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

 <!-- jQuery library -->
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
 
 <!-- Latest compiled JavaScript -->
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 


</head>

<body class="d-flex flex-column min-vh-100">
    {% url 'logout' as url_logout %}
    {% url 'login' as url_login %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'pokedex:home' %}">ThePokeymenTCG</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'pokedex:home' %}">Home</a></li>
            <li><a href="{% url 'pokedex:loadInitialData' %}">Load Initial Data</a></li>
            <li><a href="{% url 'pokedex:pokemon_list' %}">Pokemon List</a></li>
            <li><a href="{% url 'pokedex:trainer_list' %}">Trainer List</a></li>
            <li><a href="{% url 'pokedex:energy_list' %}">Energy List</a></li>
            <li><a href="{% url 'pokedex:searchInput' %}">Search for cards</a></li>
            <li><a href="{% url 'cardData:showData' %}">Card data</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <div class="col-auto d-flex align-items-center">
                        login: {{user.username}}
                    </div>
                    <div class="col-auto">
                        <form action="{{url_logout}}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary ms-3 pull-right"
                                id="logbtn">Logout</button>
                        </form>
                    </div>
                </li>
                {% else %}
                <div class="col">
                    <a class="btn btn-primary" href="{{ url_login }}" role="button">Login</a>
                </div>
                {% endif %}
          </ul>
        </div>
    </nav> 
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-7 d-flex align-items-center">
                        <div class="row" style="width: 110%">
                            <div class="col">
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
        </ul>
        {% endif %}
        {% block content %}
        {% endblock content %}
    </div>
</body>

{% block js %}
{% endblock js %}


</html>